import ToastManager from "@/lib/utils/ToastManager";
import "./globals.css";
import { Inter } from "next/font/google"
import ClientWrapper from "@/components/custom/Home/ClientWrapper";
import { ThemeProvider } from "@/components/themes/ThemeProvider";

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastManager />
          <ClientWrapper>
            {children}
          </ClientWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
